//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_15_WPF_Climbing_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimbIndoor
    {
        public int ClimbID { get; set; }
        public string ClimbName { get; set; }
        public bool ClimbDone { get; set; }
        public string ClimbLocation { get; set; }
        public string ClimbGrade { get; set; }
    }
}
