//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_15_WPF_Climbing_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClimbingDBEntities : DbContext
    {
        public ClimbingDBEntities()
            : base("name=ClimbingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClimbIndoor> ClimbIndoors { get; set; }
        public virtual DbSet<ClimbOutdoor> ClimbOutdoors { get; set; }
    }
}
